stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/depression_data.csv
    outs:
      - data/raw
  
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
    outs:
      - data/clean
  
  model_training:
    cmd: python src/model_train.py
    deps:
      - src/model_train.py
      - data/clean/train.csv
    outs:
      - mlruns/
